# This workflow updates any datasets that come from the dxy China scraping workflow

name: china-dxy-update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the autoupdate branch
on:
  schedule:
    - cron : '45 23 * * *' # will run this script at 7:45 PM EST daily (setting 8 PM crossed dateline and was confusing)

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "autoupdate"
  build:
    name: china-update
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #install R
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.3'
    #Install curl 
    - name: install curl
      run: sudo apt-get install libcurl4-openssl-dev
    #Install R package dependencies
    - name: Install dependencies
      run: Rscript -e  "install.packages(c('curl', 'dplyr', 'tidyr', 'stringr', 'here', 'httr', 'xml2', 'rvest'), repos = 'https://cloud.r-project.org', dependencies = NA)" 
      
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
   
    #scrape data from github
    - name: Process data from html
      run: Rscript china/China_casedata/extract-dxy-case-counts.R

    #Commit changes to repo to repo
    - name: Commit files
      run: |
        timestamp=$(date -u)
        git status
        git config --local user.email "actions@users.noreply.github.com"
        git config --local user.name "Automated Publisher"
        git add  china/China_casedata/*
        git commit -m "china-dxy autoupdate : ${timestamp}"
        git status
    # Push changes
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master

    # Send email with status
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.CEID_GMAIL_USERNAME }}
        password: ${{ secrets.CEID_GMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: mvevans89@gmail.com
        # from email name
        from: COVID-19-DATA repo autoupate

