# This workflow updates any datasets that originally come from a github repo

name: github-update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the autoupdate branch
on:
  schedule:
    - cron : '0 12 * * *' # will run this script at 8 AM EDT daily
    #- cron: '*/10 * * * *' #runs every ten minutes to test

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "autoupdate"
  build:
    name: github-autoupdate
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     #install R
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.3'
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    #scrape data from github
    - name: Scrape data from Github
      run: Rscript  github_data_update.R
    #Push back to repo
    - name: Commit files
      run: |
        timestamp=$(date -u)
        git config --local user.email "actions@users.noreply.github.com"
        git config --local user.name "Automated Publisher"
        git add global/canada_case_data_ishaberry/*
        git commit -m "Github autoupdate : ${timestamp}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master

    # Send email with status
    - name: Send mail
      # if: always() #runs always
      if: ${{ failure() }} #runs only if job fails
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.CEID_GMAIL_USERNAME }}
        password: ${{ secrets.CEID_GMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: emarty@uga.edu, john.king1@uga.edu
        # from email name
        from: COVID-19-DATA repo autoupate