# This workflow compiles the maps for the 2019-Coronavirus-Tracker

name: intervention-data-update


# Controls when the action will run. 
on: 
  schedule:
  - cron: '0 22 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  
jobs: 

  build: 
    name: intervention
    
    runs-on: ubuntu-latest
    
    #Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    #install R
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.3'
        
    #install curl
    - name: install curl
      run: sudo apt-get install libcurl4-openssl-dev
      
    #Install R package dependencies
    - name: Install dependencies
      run: Rscript -e  "install.packages(c('dplyr', 'tidyr', 'googledrive', 'googlesheets4', 'lubridate'), repos = 'https://cloud.r-project.org', dependencies = NA)" 

    - uses: actions/checkout@master
    
    # Scrape US state data
    - name: Scrape us state inerventions
      run: Rscript 'US/us-state-intervention-data/get-state-intervention-data.R'
      
      
    # Scrape Us county data
    - name: Scrape us county interventions
      run: Rscript 'georgia/ga-county-intervention-data/get-county-intervention-data.R'

      # Push back to repo
    - name: Commit files
      run: |
        timestamp=$(date -u)
        git config --local user.email "actions@users.noreply.github.com"
        git config --local user.name "Automated Publisher"  
        git add 'US/us-state-intervention-data/US_raw_state_interventions.csv'
        git add 'US/us-state-intervention-data/US_state_intervention_time_series.csv'
        git add 'georgia/ga-county-intervention-data/GA_raw_county_interventions.csv'
        git add 'georgia/ga-county-intervention-data/GA_county_intervention_time_series.csv'
        git status
        git commit -m "interactive map autoupdate : ${timestamp}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master

    # Send email with status
    - name: Send mail
      # if: always() #runs always
      if: ${{ failure() }} #runs only if job fails
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.CEID_GMAIL_USERNAME }}
        password: ${{ secrets.CEID_GMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: emarty@uga.edu, john.king1@uga.edu
        # from email name
        from: COVID-19-DATA repo autoupate


