# This workflow scrapes US cases from wikipedia

name: us-cases-wiki-scrape

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the autoupdate branch
on:
  schedule:
    - cron : '0 2,10 * * *' # will run this script at 6 AM & 10 PM EST daily 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "autoupdate"
  build:
    name: us-wiki-scrape
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #install R
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.2'
    #Install curl 
    - name: install curl
      run: sudo apt-get install libcurl4-openssl-dev
    #Install R package dependencies
    - name: Install dependencies
      run: Rscript -e  "install.packages(c('xml2', 'rvest', 'USAboundaries'), repos = 'https://cloud.r-project.org', dependencies = NA)" 

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    #scrape data from github
    - name: Scrape data from Wikipedia
      run: Rscript  US/US_wikipedia_cases_fatalities/read_UScases_wikipedia.R

    #Push back to repo
    - name: Commit files
      run: |
        timestamp=$(date -u)
        git config --local user.email "actions@users.noreply.github.com"
        git config --local user.name "Automated Publisher"
        git add US/US_wikipedia_cases_fatalities/UScases_by_state_wikipedia.csv
        git add US/US_wikipedia_cases_fatalities/USfatalities_by_state_wikipedia.csv
        git status
        git commit -m "us-wiki autoupdate : ${timestamp}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master

    # Send email with status (from ceid.ecology@gmail.com)
    - name: Send mail
      # if: always() #runs always
      if: ${{ failure() }} #runs only if job fails
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.CEID_GMAIL_USERNAME }}
        password: ${{ secrets.CEID_GMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: emarty@uga.edu, john.king1@uga.edu
        # from email name
        from: COVID-19-DATA repo autoupate
