# This workflow compiles the maps for the 2019-Coronavirus-Tracker

name: world-data-wiki-scrape


# Controls when the action will run. 
on: 
  schedule:
  - cron: '30 1 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  
jobs: 

  build: 
    name: scrape-world
    
    runs-on: ubuntu-latest
    
    #Steps represent a sequence of tasks that will be execusted as part of the job
    steps:
    #install R
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.3'
        
    #install curl
    - name: install curl
      run: sudo apt-get install libcurl4-openssl-dev
      
    #Install R package dependencies
    - name: Install dependencies
      run: Rscript -e  "install.packages(c('dplyr', 'tidyr', 'padr', 'rvest', 'tibbletime', 'stringr'), repos = 'https://cloud.r-project.org', dependencies = NA)" 

    - uses: actions/checkout@master
    
    # Scrape world data
    - name: Scrape world case data
      run: Rscript 'global/global_cases_by_country/get-world-data.R'
      
      # Push back to repo
    - name: Commit files
      run: |
        timestamp=$(date -u)
        git config --local user.email "actions@users.noreply.github.com"
        git config --local user.name "Automated Publisher"  
        git add global/global_cases_by_country/worldCases.csv
        git status
        git commit -m "interactive map autoupdate : ${timestamp} ${GITHUB_SHA}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master


