# This workflow compiles the maps for the 2019-Coronavirus-Tracker

name: world-data-wiki-scrape


# Controls when the action will run. 
on: 
  schedule:
  - cron: '30 1 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  
jobs: 

  build: 
    name: scrape-world
    
    runs-on: ubuntu-latest
    
    #Steps represent a sequence of tasks that will be execusted as part of the job
    steps:
    #install R
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.3'
        
    #install curl
    - name: install curl
      run: sudo apt-get install libcurl4-openssl-dev
      
    #Install R package dependencies
    - name: Install dependencies
      run: Rscript -e  "install.packages(c('dplyr', 'tidyr', 'padr', 'rvest', 'tibbletime', 'stringr'), repos = 'https://cloud.r-project.org', dependencies = NA)" 

    - uses: actions/checkout@master
    
    # Scrape world data
    - name: Scrape world case data
      run: Rscript 'global/global_cases_by_country/get-world-data.R'
      
      # Push back to repo
    - name: Commit files
      run: |
        timestamp=$(date -u)
        git config --local user.email "actions@users.noreply.github.com"
        git config --local user.name "Automated Publisher"  
        git add global/global_cases_by_country/worldCases.csv
        git status
        git commit -m "interactive map autoupdate : ${timestamp}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master

        # Send email with status from ceid.ecology@gmail.com
    - name: Send mail
      # if: always() #runs always
      if: ${{ failure() }} #runs only if job fails
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.CEID_GMAIL_USERNAME }}
        password: ${{ secrets.CEID_GMAIL_PASSWORD }} #app password
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: emarty@uga.edu, john.king1@uga.edu
        # from email name
        from: COVID-19-DATA repo autoupate


